### ISSUE TITLE
V10 deprecation warnings.

### ISSUE THREAD

**Issue by tehguitarist** [MoonIsFalling/pf2e-display-actions#10]
Nothing major, just some deprecation warnings for the module.json
<img width="955" alt="Screenshot 2023-02-01 at 7 22 19 pm" src="https://user-images.githubusercontent.com/28495826/215989892-a7576ddd-f0c2-4f80-b5e1-c850301e9b1b.png">

**Comment by MoonIsFalling** [comment]
Originally this was an artifact for the support of older foundry versions.
As I personally verify V10 a break was bound to happen.
