### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by Cerender** [MoonIsFalling/pf2e-display-actions#15]
Pictures not showing any more.

I edited modle.js from:
    this.actionImage = "/systems/pf2e/icons/actions/OneAction.webp";
    this.reactionImage = "/systems/pf2e/icons/actions/Reaction.webp";
    
to:
    this.actionImage = "systems/pf2e/icons/actions/OneAction.webp";
    this.reactionImage = "systems/pf2e/icons/actions/Reaction.webp";

To get it working locally.

**Comment by MoonIsFalling** [comment]
Hi,
Sorry for the late response.
I couldn't replicate the issue, but I will be using the path without leading forward slash.
Thank you for telling me.
