### ISSUE TITLE
Feature Request: More compact UI (or a UI that scales better with the window)

### ISSUE THREAD

**Issue by tehguitarist** [MoonIsFalling/pf2e-display-actions#8]
Love the module! Actually picked it up at the request of one of my players.

Currently the UI is a little big, and scaling down doesn't affect the action buttons, would be great to have something quite compact (like the Always HP UI or Simple Calendars compact UI).

I couldn't find an obvious place where the icons were scaled, but my typescript knowledge is worse than my javascript knowledge (which is rudimentary at best).

If I get some time I'll see if I can follow what's going on and make a PR. Obviously there needs to be a touch of padding between the text and text inputs (could possibly be dropdowns?) and stripping out "selected" from the the button text would probably necessitate an alert to say "No tokens selected"

I did some CSS hacking with dev tools and came up with this (dark theme is from Dorako UI): 
<img width="350" alt="Screenshot 2023-01-30 at 10 55 47 am" src="https://user-images.githubusercontent.com/28495826/215363394-b17e5378-b7ea-46ae-bfa6-a98c7b737f27.png">

**Comment by MoonIsFalling** [comment]
Thanks for the kind feedback.

I am no CSS wizard, I'll see what I can do. If you are willing to give me your modifications, I could incorpate them and credit you.

**Comment by tehguitarist** [comment]
I'll see if I can find the right modifications and make a PR soon for you. CSS is definitely a bit of a dark art!

**Comment by tehguitarist** [comment]
Ended up working it out, it's not perfect (some title bar buttons are missing unless you expand the window) But hey. A better solution long term is probably to make everything scale with the window, and then save the window size in user settings. 
Pull Request #9

**Comment by MoonIsFalling** [comment]
Thank you for your contribution.
I think I found out how to make it more compact, but also scale if needed. 
I am closing this issue for now.
